# Use root/example as user/password credentials
version: '3.1'

services:
  # app Ã© a nossa API
  # app:
  #   build: .
  #   container_name: loja-de-carro-api
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/home/node/app
  #   entrypoint: ./.docker/entrypoint.sh
  #   depends_on:
  #     - db

  # MySQL
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: carshop
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  # Cliente para acessar o MySQL
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
